"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.rolesRoutes = void 0;
const role_controller_1 = require("../controller/role.controller");
const rolesRoutes = (router) => {
    // router.post('/api/roles',checkPermission('AddRole'), createRole);
    // router.get('/api/roles', checkPermission('ListeRole'),getAllRoles);
    // router.get('/api/roles/simple/:id', getSimpleRole);
    // router.get('/api/roles/:id', checkPermission ('ViewRole'),getRole);
    // router.delete('/api/roles/:id',  checkPermission('DeleteRole'),deleteRole);
    // router.delete('/api/rolePermission/:id',  checkPermission('DeleteRole'),deleteRolePermission);
    // router.put('/api/roles/:id', checkPermission('EditRole'),updateRole);
    // router.post('/api/roles/permissions',checkPermission('AddRole'), createRolePermeission);
    // router.post('/api/roles',checkPermission('AddRole'), createRole);
    // router.get('/api/roles',checkPermission('ListRole'),getAllRoles);
    // router.get('/api/rolesp',checkPermission('ListRoleP'),getAllRole);
    // router.get('/api/roles/simple/:id', checkPermission('ViewSimpeRole'),getSimpleRole);
    // router.get('/api/roles/:id',checkPermission('ViewRole'),getRole);
    // router.delete('/api/roles/:id',checkPermission('DeleteRole'),deleteRole);
    // router.delete('/api/rolePermission/:id',checkPermission('DeleteRolePermission'),deleteRolePermission);
    // router.get('/api/resteante/roles/:userId',checkPermission('RolesNotIn'), getRolesNotIn);
    // router.put('/api/roles/:id',checkPermission('EditRole'),updateRole);
    // router.post('/api/roles/permissions',checkPermission('AddRolePermission'), createRolePermission);
    router.post('/api/roles', role_controller_1.createRole);
    router.get('/api/roles', role_controller_1.getAllRoles);
    router.get('/api/rolesp', role_controller_1.getAllRole);
    router.get('/api/roles/simple/:id', role_controller_1.getSimpleRole);
    router.get('/api/roles/:id', role_controller_1.getRole);
    router.delete('/api/roles/:id', role_controller_1.deleteRole);
    router.delete('/api/rolePermission/:id', role_controller_1.deleteRolePermission);
    router.get('/api/resteante/roles/:userId', role_controller_1.getRolesNotIn);
    router.put('/api/roles/:id', role_controller_1.updateRole);
    router.post('/api/roles/permissions', role_controller_1.createRolePermission);
};
exports.rolesRoutes = rolesRoutes;
