name: app_expenses
description: "SenaTrack - Application de gestion des dépenses"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  fl_chart: ^1.2.0
  image_picker: ^1.0.0
  shared_preferences: ^2.5.5
  path: ^1.9.1
  crypto: ^3.0.7
  sqflite: ^2.4.2
  intl: ^0.20.2
  csv: ^6.0.0
  excel: ^4.0.6
  path_provider: ^2.1.2
  share_plus: ^9.0.0
  flutter_svg: ^2.0.10
  dio: ^5.11.0
  http: ^1.6.0
  flutter_secure_storage: ^10.3.1
  provider: ^6.1.2
  timeago: ^3.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true # Active la génération automatique de traductions

  assets:
    - assets/images/logo_romas0.png
    - assets/images/green_flowers_bg.png

  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
        - asset: assets/fonts/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/PlusJakartaSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
          weight: 700